__include__: [
  '../dataset/sputum_aug_detection.yml',
  '../runtime.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

output_dir: ./output/rtdetrv2_r50vd_sputum_aug



# cd /home/ubuntu/lsn/project_new/RT-DETR-main
# python rtdetrv2_pytorch/tools/train.py \
#   -c rtdetrv2_pytorch/configs/rtdetrv2/rtdetrv2_r50vd_sputum_aug.yml \
#   --use-amp --seed 42 -d cuda:0


early_stopping_patience: 10
early_stopping_min_delta: 0.001

epoches: 200  # 5万张数据+R50模型，类别不平衡任务建议120-150 epochs，早停机制会在验证指标不提升时自动停止

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
      weight_decay: 0.0001
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.0
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 2000

RTDETRCriterionv2:
  class_weight_file: DATA/SputumCell/split_dataset_aug/analysis/class_balance_class_weights.json
  class_weight_key: weight
  class_weight_power: 1.0


